apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8test-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kirosoft/k8test-repo.git
    targetRevision: HEAD
    path: charts/k8test
    helm:
      parameters:
        - name: image.tag
          value: 851f74dd5d36db2132e1751d2ee19b9f987c777a
        - name: image.repository
          value: k8demoacr.azurecr.io/k8test
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
