apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: k8test-staging
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/kirosoft/k8test-gitops-repo.git
        targetRevision: HEAD
        path: envs/staging/k8test
        helm:
            valueFiles:
            - values.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: staging
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
